### PR TITLE
Initial Thai ReadMe translation.

### PR DESCRIPTION
**Pull request by Gnoyoyo**

### CODE REVIEW

**Comment by narze** [comment]
Do you plan to link from the original readme?

**Comment by Gnoyoyo** [comment]
That is a good idea! I'll add it then

**Comment by narze** [comment]
Thanks, by the way are you planning to translate all of the existing content?

**Comment by Gnoyoyo** [comment]
I would like to leave the content to someone else that wants to contribute.

**Comment by narze** [comment]
🙆

**Pull request merged**
