### PR TITLE
Add index frontend page

### PR DESCRIPTION
**Pull request by kasettakorn**
Add frontend (index.html)

### CODE REVIEW

**Comment by narze** [comment]
Could you please show me the frontend screenshot?

**Comment by kasettakorn** [comment]
> Could you please show me the frontend screenshot?

**Comment by kasettakorn** [comment]
> Could you please show me the frontend screenshot?

https://drive.google.com/file/d/1OvpsWkKkXmmMJRkUe8evboCLujoRmXsK/view?usp=sharing

**Comment by narze** [comment]
It looks ok, but I don't think we should add specific branding, to make this repo re-useable in the next years to come krub.

By the way, I'll tag this as `hacktoberfest-accepted` to make it count, thanks for contribution!

**Pull request closed without merging**
